### PR TITLE
[ISSUE-250]add a solution for Predict the winner problem

### PR DESCRIPTION
**Pull request by ravi0213**
### Issue Id you have worked upon - 
#250 

### Briefly explain your program logic - 
Approach: Dynamic Programming
As we know both players play optimally,
If a player pick an element from either end then next player will also try to maximize the score and will try to minimize other player's score.
So for subarray `i` and `j`, the recurrence would be,
      dp[i][j] = Math.max(
                    a[i] + Math.min(dp[i + 1][j - 1], dp[i + 2][j]),
                    a[j] + Math.min(dp[i + 1][j - 1], dp[i][j - 2])
                  )
and base case would be dp[i][i] = a[i]
Complexity:
Time complexity = O(n * n) // as we have 2 dp states, the complexity is squared.
Space complexity = O(n * n) // as we are calculating an answer for each subarray, the complexity is also squared.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
Screen Shot 2021-10-05 at 18 38 57
Screen Shot 2021-10-05 at 18 39 54

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied even after successful merge then I can be banned from the repository and hacktoberfest.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by ravi0213** [comment]
@SarthakKeshari Kindly review the PR.
In the screenshots, The first two lines are input and the last line is output.

Thanks

**Comment by SarthakKeshari** [comment]
@ravi0213,
Kindly comment you code in the logical sections that you have written.

**Comment by ravi0213** [comment]
@SarthakKeshari I have updated it and added comments in the program.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@ravi0213,
I Appreciate the code presentation, organization and commenting
Appreciating by **Leveling up your question from level2 to level3**

**Pull request merged**
