### PR TITLE
Diagonal

### PR DESCRIPTION
**Pull request by Ln11211**
### Issue Id you have worked upon - 
 Zigzag traversal of Matrix #92 

### Briefly explain your program logic - 
Firstly the order of the matrix is entered and then the elements one by one ,which are stored. Then the elements are printed according to the diagonal order using "for loop".

### Screenshots(Attach 2 screenshots of your own input and output) - 
image

image

image

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by Ln11211** [comment]
@SarthakKeshari sir, please review this, thank you..

**Comment by SarthakKeshari** [comment]
@Ln11211,
Kindly add a few more comments in between thinking about explaining it to a beginner who might be visiting your code.

**Comment by Ln11211** [comment]
@SarthakKeshari sir, ok, I'll do it right away...

**Comment by Ln11211** [comment]
@SarthakKeshari sir, done , can you please check now ?, do let me know if you need any more additions to the code...

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
