### PR TITLE
Create birthday.java

### PR DESCRIPTION
**Pull request by Ln11211**
### Issue Id you have worked upon - 
Birthday Cake Candles #5 

### Briefly explain your program logic - 
The program first takes the input from the user for the number of candles present on the cake and then takes the heights of each candle and returns the number of tallest candles present on the cake. An array is used that stores the input of candle heights and then it is sorted in ascending order to determine the tallest candle and count how many such candles are present.

### Screenshots(Attach 2 screenshots of sample input and output) - 
ss1

ss2

ss3
<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Ln11211,
It was showing drafted for your PR, do you want it to be reviewed?

**Comment by Ln11211** [comment]
@SarthakKeshari, yes I made a draft pr because I got a small problem...
 so I updated my code with the question as mention in guidlines and now it won't apper in the compare and pull request section, Although the original code has the question as a comment, it is not reflecting here.

image

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari, yes I made a draft pr because I got a small problem... so I updated my code with the question as mentioned in the guidlines and now it won't apper in the compare and pull request section, Although the original code has the question as a comment, it is not reflecting here.
> 
> image

Great to see such a responsible behaviour

**Comment by Ln11211** [comment]
well. I commited the latest changes, now can you review it and merge ?

**Review by SarthakKeshari — CHANGES_REQUESTED** [review]
Since code has been written in one file only, but 7 other files can be seen to be altered. Kindly retify this.

**Comment by Ln11211** [comment]
image
@SarthakKeshari sir, will this fix the problem ?

**Comment by SarthakKeshari** [comment]
Yes

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
