### PR TITLE
The longest ascending sequence

### PR DESCRIPTION
**Pull request by erickcernarequejo**
### Issue Id you have worked upon - 

#47 

Created a program to check the longest ascending sequence in an array

### Briefly explain your program logic - 
The array is traversed to position n - 1, verifying if the value with index i is less than the next, if that happens, it increases the value of the counter by 1 because the sequence condition would be fulfilled in the first two elements and so on. increases. If one element is not a sequence of another, its value is stored in the maxTmp variable and pos, and then compared with the counter that will repeat step 1. Finally, the two variables are compared to determine which was the longest sequence and print from pos to pos + max.

### Screenshots(Attach 2 screenshots of sample input and output) - 

```Example 1: ```

image

```Example 2: ```

image

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@erickcernarequejo,
Make are short change in the program and instead of printint the length of longest ascending sequence in an array. Print the elements of longest ascending sequence in an array

**Comment by erickcernarequejo** [comment]
> @erickcernarequejo, Make are short change in the program and instead of printing the length of longest ascending sequence in an array. Print the elements of longest ascending sequence in an array

ok i just added the indicated solution.

**Comment by SarthakKeshari** [comment]
@erickcernarequejo,
Kindly mention issue id and change the screenshots to a new one based on the changes you have made to the question

**Comment by erickcernarequejo** [comment]
> as
ok i just added the indicated solution.

**Comment by SarthakKeshari** [comment]
@erickcernarequejo,
Kindly add comments to logical sections of your code

**Comment by erickcernarequejo** [comment]
> @erickcernarequejo, Kindly add comments to logical sections of your code

Ok, I add comments

**Review by SarthakKeshari — APPROVED** [review]

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
