### PR TITLE
Solution to Searching a key in rotated sorted array.

### PR DESCRIPTION
**Pull request by venkatsgithub1**
### Issue Id you have worked upon - 
issue #363 

### Briefly explain your program logic - 
The solution program uses binary search to find and element in the sorted but rotated array.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Input:
image
Output:
image

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

- [x] I have mentioned the question as comment in my solution file.<br>
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>
- [x] I confirm that I have not copied the code from anywhere. In case its found that I have copied even after successful merge then I can be banned from the repository and hacktoberfest.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by venkatsgithub1** [comment]
@SarthakKeshari  - Added commit c6f3c198ce19a68fcaa7b0e168eed5552318af2e with question.

**Comment by venkatsgithub1** [comment]
@SarthakKeshari  - Added question as comment in solution file, please review commit: 3d5a5c2572defcbbfa14dcfe5f70f5e3ade9e626

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari - Added question as comment in solution file, please review commit: [3d5a5c2](https://github.com/SarthakKeshari/Java-Questions-and-Solutions/commit/3d5a5c2572defcbbfa14dcfe5f70f5e3ade9e626)

File is updated now

**Comment by SarthakKeshari** [comment]
> @venkatsgithub1, Kindly fill the checklist by agreeing to its terms

Kindly look into this too

**Pull request merged**
