### PR TITLE
 factorial-by-loops.java added

### PR DESCRIPTION
**Pull request by vish-han**
### Issue/Solution Id you have worked upon - 
#16 

### Briefly explain your program logic - 
Factorial of a number "n" is n*(n-1)*.....*2*1

### Screenshots(Attach 2 screenshots of sample input and output) - 

OUTPUT

OUTPUT2

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly fill the above details template, iorder to get your PR merged.

**Review by SarthakKeshari — CHANGES_REQUESTED** [review]
Kindly fill the PR template.

**Comment by MohammedHassan07** [comment]
@SarthakKeshari 
Kindly assign this issue to me

**Comment by SarthakKeshari** [comment]
@vish-han,
Deadline for making requested changes - 30/09/2021

**Comment by SarthakKeshari** [comment]
@vish-han,
Deadline for making requested changes - 30/09/2021
No making the required changes may lead to PR rejection.

**Comment by SarthakKeshari** [comment]
@vish-han,
Deadline for making requested changes - 30/09/2021
Not making the required changes may lead to PR rejection.

**Comment by vish-han** [comment]
Ok I will do it now

**Comment by vish-han** [comment]
Is it ok now????

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly
1) Attach 2 output screenshots
2) Comment your code to make it understandable
3) Also add the question description to the solution file as comment

**Comment by vish-han** [comment]
Okkkkk

**Comment by vish-han** [comment]
I have added the screen shots , please review it

**Comment by SarthakKeshari** [comment]
> @vish-han, Kindly
> 
> 1. Attach 2 output screenshots
> 2. Comment your code to make it understandable
> 3. Also add the question description to the solution file as comment

@vish-han,
Kindly address all the queries I have mentioned without fail

**Comment by vish-han** [comment]
should i add the question and comment in the file ?
or PR documentation

**Comment by SarthakKeshari** [comment]
> should i add the question and comment in the file ? or PR documentation

In the solution file

**Comment by vish-han** [comment]
is it ok now please check and let me know?

**Comment by vish-han** [comment]
???

**Comment by SarthakKeshari** [comment]
Good to go

**Review by SarthakKeshari — APPROVED** [review]

**Comment by vish-han** [comment]
bro is this repo under hacktoberfest??
can u add the hacktoberfest accepted tag??

**Comment by SarthakKeshari** [comment]
Level 0 questions ain't under hacktober questions... Try to grab harder problems

**Pull request merged**
