### PR TITLE
Create Rotate_Array.java

### PR DESCRIPTION
**Pull request by nik132-eng**
There are three solutions of rotate array

### Issue Id you have worked upon - #76 
@SarthakKeshari 

### Briefly explain your program logic - 
already added with the comments

### Screenshots(Attach 2 screenshots of your own input and output) - 
image

image

<br>

### Checklist:
Eg - If your code follows the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[] I have mentioned the question as a comment in my solution file.<br>
[] My code follows the guidelines of this project.<br>
[] I have performed a self-review of my own code.<br>
[] I have commented on my code.<br>
[] My code gives the correct output.<br>
[] I confirm that I have not copied the code from anywhere. In case it's found that I have copied I can be banned from the repository.<br>

[] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@nik132-eng,
Kindly create an issue first and get it assigned to you.
In issue id you'll be mentioned the auto generated issue id instead of username.
Kindly go through CONTRIBUTING.md for further references

Since this had been communicated to you in #72. So, I will be closing this PRs. Follow the guidelines

**Comment by nik132-eng** [comment]
sir, I follow that step, firstly created the issue and that you assign to me #76.
you can check the username

image

please sir don't where I done a mistake can you tell me.

**Comment by nik132-eng** [comment]
@SarthakKeshari sir, I don't know what to do now. 
can you help me

**Comment by SarthakKeshari** [comment]
> sir, I follow that step, firstly created the issue and that you assign to me #76. you can check the username
> 
> image
> 
> please sir don't where I done a mistake can you tell me.

Issue ID didn't show up on the PR template. So I closed it. No worries. Go ahead now.

**Comment by nik132-eng** [comment]
ok sir, thank you.
can you merge this now?

**Comment by SarthakKeshari** [comment]
> ok sir, thank you. can you merge this now?

@nik132-eng,
A very good presentation of code and comment.
Appreciating👏 by **leveling up your question from level2 to level3**

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@nik132-eng,
Just fill the checklist then its good to go

**Pull request merged**
