### PR TITLE
search in Infinite Array Added

### PR DESCRIPTION
**Pull request by vish-han**
### Issue Id you have worked upon - 
#71

### Briefly explain your program logic - 
To find an element in an infinite sorted array , you have to search for the element in chunks or ranges in order to find the start 
and end of the range , after you find the range you can apply normal binary search.

### Screenshots(Attach 2 screenshots of your own input and output) - 

array
array2
<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by vish-han** [comment]
please review the code and merge it , please add the hackoberfest-accepted and hacktoberfest tag.

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly add few more comments so that for a beginner the code becomes easy to understand

**Comment by vish-han** [comment]
Ok sir

**Comment by vish-han** [comment]
I have added the comment please review and let me know if u want some other changes

**Comment by vish-han** [comment]
Please review it asap

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
