### PR TITLE
Palindrome

### PR DESCRIPTION
**Pull request by satyam878**
### Issue Id you have worked upon - 
#53
Created a program to check palindrome string

### Briefly explain your program logic - 
I just took two pointers traversing from starting and ending of string and compared each character. If each character is matched then it would be a palindrome , if it doesn't matches so we directly print not palindrome and break out of the loop.

### Screenshots(Attach 2 screenshots of sample input and output) - 
Attach here

<br>

Screenshot (167)
Screenshot (168)
### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

 [x ]I have given the question in the above statement.<br>
 [x]My code follows the guideline of this project.<br>
[x] I have performed a self-review of my own code..<br>
[x] I have commented my code. <br>
[x] My code gives correct output.<br>
[x]I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x]I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly attach screen shot, fill the checklist and comment your code

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly respond. In case of no responce PR will be closed by 04/10/2021

**Comment by satyam878** [comment]
Please review my work @SarthakKeshari

**Comment by SarthakKeshari** [comment]
@satyam878,
Kindly refer fill the checklist properly.

**Comment by SarthakKeshari** [comment]
@satyam878,
Checklist is filled - 

[] Hello ➡  [x] Hello ✔

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
