### PR TITLE
Create MaximumSubArray

### PR DESCRIPTION
**Pull request by vyom18**
### Issue Id you have worked upon - 
245

### Briefly explain your program logic - 
Your answer
I have created a file based on kadane's algorithm

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
Input:-
image
Output:-
image

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@vyom18,
Kindly close this issue. Follow the guidelines and create a new one after all the steps present in CONTRIBUTING.md are followed

**Comment by SarthakKeshari** [comment]
Kindly close this PR. Follow the guidelines and create a new PR after all the steps present in CONTRIBUTING.md are followed

**Comment by vyom18** [comment]
Ok sure I will but  please accept for hacktoberfest

**Comment by vyom18** [comment]
I have done please look into it

**Comment by SarthakKeshari** [comment]
@vyom18,
Kindly create an issue get it assigned and write the issue id in PR template

**Comment by SarthakKeshari** [comment]
@vyom18,
Kindly write issue id as #245 instead of 245

**Comment by SarthakKeshari** [comment]
@vyom18,
This PR will be marked as invalid by 08/10/2021(6PM). Kindly respond by either closing it or making the required changes

**Pull request closed without merging**
