### PR TITLE
inversions count

### PR DESCRIPTION
**Pull request by RAshid602**
**Issue ld you have worked upon-**
#179 

**Briefly explain you code logic**
For an array, inversion count indicates how far (or close) the array is from being sorted.
 If array is already sorted then the inversion count is 0.likewise, If an array is sorted in the reverse order then the inversion count is the maximum. 

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]
Screenshot 2021-10-03 173404
ans2

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by RAshid602** [comment]
I have done the work, kindly merge it.
if any issue let me know i will edit it.

**Comment by SarthakKeshari** [comment]
@RAshid602,
Kindly follow the PR template. Template part above the checklist seems to be removed. Rectify it and update

**Comment by RAshid602** [comment]
Now its done.
Thank you for your support.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@RAshid602,
Issue id is your question id. Kindly change it.

**Comment by RAshid602** [comment]
hey @SarthakKeshari  i am unable to find my question id,i know it sound silly but this is my first contribution,.
So kindly guide me.

**Comment by SarthakKeshari** [comment]
> hey @SarthakKeshari i am unable to find my question id,i know it sound silly but this is my first contribution,. So kindly guide me.

@RAshid602,
I will help you out.

**Comment by SarthakKeshari** [comment]
image

#179 is your Question ID

**Comment by RAshid602** [comment]
The changes has been made, Thank you for your support!

**Pull request merged**
