### PR TITLE
Burst_Balloon.java

### PR DESCRIPTION
**Pull request by Sakshamgupta90**
### Issue Id you have worked upon - 
#239 

### Briefly explain your program logic - 
The problem is solved using DP.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Screenshot 2021-10-05 at 10 53 01 AM

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied even after successful merge then I can be banned from the repository and hacktoberfest.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

@SarthakKeshari please review this PR

### CODE REVIEW

**Review by SarthakKeshari — APPROVED** [review]

**Comment by Sakshamgupta90** [comment]
@SarthakKeshari why this project got excluded from hacktoberfest?

**Comment by SarthakKeshari** [comment]
@Sakshamgupta90,
No info received yet.

**Comment by Sakshamgupta90** [comment]
Screenshot 2021-10-16 at 8 04 55 PM
@SarthakKeshari  please see this!

**Comment by SarthakKeshari** [comment]
> Screenshot 2021-10-16 at 8 04 55 PM
> 
> @SarthakKeshari please see this!

@Sakshamgupta90,
Got to know about from some contributors. Hence did put up the announcement a couple of days back #439 . I haven't received any mail from their end.

**Pull request merged**
