### PR TITLE
Solved LRU_Cache.java

### PR DESCRIPTION
**Pull request by Sakshamgupta90**
### Issue Id you have worked upon - 
#237 

### Briefly explain your program logic - 
So basically using Hashmap and doubly linked list it becomes quite easy to solve this question. A simple dry run of the question will help you how it works.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Screenshot 2021-10-05 at 12 18 32 AM

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied even after successful merge then I can be banned from the repository and hacktoberfest.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by Sakshamgupta90** [comment]
@SarthakKeshari please review my PR

**Comment by SarthakKeshari** [comment]
@Sakshamgupta90,
Kindly mention issue id properly.
And add comments to the logical parts of your solution

**Comment by Sakshamgupta90** [comment]
@SarthakKeshari sorry for that! 
could you please tell me what does that mean "And add comments to the logical parts of your solution"
Actually I'm new in contribution so I didnt know much!

**Comment by SarthakKeshari** [comment]
@Sakshamgupta90,

For example if we write code to add two numbers - 
public class Add
{
  public static void main(String[] args) {
    int a = 1;
    int b = 2;
    int sum = a + b; // Adding two numbers
    System.out.println(sum); // Printing the sum
  }
}

Here, Adding two numbers and Printing the sum are comments.
So like this you need to write the comments in logical parts of the code.

**Comment by Sakshamgupta90** [comment]
okay I will do it

**Comment by SarthakKeshari** [comment]
@Sakshamgupta90,
Kindly add comments to the logical parts of your solution

**Comment by Sakshamgupta90** [comment]
@SarthakKeshari yeah doing

**Comment by Sakshamgupta90** [comment]
@SarthakKeshari please review ! I think I have made it little bit readable!

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
