### PR TITLE
semisort1 problem

### PR DESCRIPTION
**Pull request by Ln11211**
Code for semisort1 problem.

### Issue Id you have worked upon - 
 Semi sort 1 #28 

### Briefly explain your program logic - 
The program is to sort half of the array in ascending and second half in descending or vice versa depending on users choice,
A java util method .sort() and a java lang method .clone() is used to do the same with some "for loops". The program is made modular for easy debugging too. This is an original work of LN11211 and not copied from anywhere.

### Screenshots(Attach 2 screenshots of sample input and output) -
seso1

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by Ln11211** [comment]
@SarthakKeshari, can you review this ?

**Comment by SarthakKeshari** [comment]
@Ln11211,
Kindly look into second screen shot its giving incorrect result.

Screenshot 2-
Ans 1 should be) 1 2 3 7 6 4
Ans 2 should be) 3 2 1 4 6 7

If you see the question carefully we need to divide the array in two halves -
For odd - 
Eg-> 5 = 3 + 2
Eg-> 7 = 4 + 3
For even -
Eg-> 6 = 3 + 3
Eg-> 8 = 4 + 4

**Comment by Ln11211** [comment]
@SarthakKeshari, earlier I wanted to ask you about this, but I assumed to only consider length/2 for even and odd lengths. I will changes it right away, thank you.

**Comment by SarthakKeshari** [comment]
> @SarthakKeshari, earlier I wanted to ask you about this, but I assumed to only consider length/2 for even and odd lengths. I will changes it right away, thank you.

No worries, it won't be counted in any negative sense. Changes for betterment of code are always welcomed

**Comment by Ln11211** [comment]
image

@SarthakKeshari done, yayyyyy

**Comment by SarthakKeshari** [comment]
@Ln11211, Good to go

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
