### PR TITLE
Armstrong number added

### PR DESCRIPTION
**Pull request by vish-han**
### Issue Id you have worked upon - 
#161

### Briefly explain your program logic - 
Armstrong number is a number that is equal to the sum of cubes of its digits. For example 0, 1, 153, 370, 371 and 407 are the Armstrong numbers.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
arm1

arm2
<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by vish-han** [comment]
please review the code and let me know if u want somechanges, please add hacktoberfest-accepted tag

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly comment your code well.

**Comment by vish-han** [comment]
@SarthakKeshari  Comments added please review it now

**Comment by vish-han** [comment]
@SarthakKeshari please review it

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
